Repository haddocking/cport, pull requests merged in 2022-05, with the labels that each got.

#31 Add PredictProtein predictor
  README.md
  etc/config.json
  requirements.txt
  src/cport/modules/loader.py
  src/cport/modules/predictprotein.py
  src/cport/url.py
  tests/.DS_Store
  tests/test_data/predictprotein_result.txt
  tests/test_predictprotein.py
Labels: enhancement, predictor

#32 Added meta-PPISP
  README.md
  etc/config.json
  src/cport/modules/loader.py
  src/cport/modules/meta_ppisp.py
  src/cport/url.py
  tests/test_data/meta_ppisp_result.txt
  tests/test_meta_ppisp.py
Labels: enhancement, predictor

#34 Add extra lints
  .darglint
  .flake8
  .github/workflows/lint.yml
  .isort.cfg
Labels: testing

#35 Code cleaning
  .darglint
  src/cport/cli.py
  src/cport/modules/cons_ppisp.py
  src/cport/modules/error.py
  src/cport/modules/ispred4.py
  src/cport/modules/loader.py
  src/cport/modules/meta_ppisp.py
  src/cport/modules/predictprotein.py
  src/cport/modules/predus2.py
  src/cport/modules/scriber.py
  src/cport/modules/send_file/__init__.py
  src/cport/modules/send_file/meta_ppisp.py
  src/cport/modules/send_file/pro_mate.py
  src/cport/modules/send_file/spider.py
  src/cport/modules/send_file/whiscy.py
  src/cport/modules/sppider.py
  src/cport/modules/tools/__init__.py
  src/cport/modules/tools/calc_sasa.py
  src/cport/modules/tools/haddock_calc_sasa.py
  src/cport/modules/tools/muscle3
  src/cport/modules/tools/naccess.config
  src/cport/modules/tools/parser.py
  src/cport/modules/tools/pdb.py
  src/cport/modules/tools/predictors.py
  src/cport/modules/tools/reconstruct_pdb.py
  src/cport/modules/tools/resdist/Makefile
  src/cport/modules/tools/resdist/resdist
  src/cport/modules/tools/resdist/resdist.cpp
  src/cport/modules/tools/resdist/resdist.o
  src/cport/modules/tools/residiues_distance.py
  src/cport/modules/tools/save_csv.py
  src/cport/modules/tools/seq.py
  src/cport/modules/tools/sequence_convert.py
  src/cport/modules/tools/threshold.py
  src/cport/modules/tools/threshold1.stat
  src/cport/modules/tools/threshold2.stat
  src/cport/modules/tools/threshold3.stat
  src/cport/modules/tools/validations.py
  src/cport/modules/tools/whiscy_hssp.py
  src/cport/modules/tools/whiscy_pdbutil.py
  src/cport/modules/utils.py
  src/cport/modules/whiscy.py
  tests/test_cons_ppisp.py
  tests/test_ispred4.py
  tests/test_meta_ppisp.py
  tests/test_predictprotein.py
  tests/test_predus2.py
  tests/test_sppider.py
  tests/test_whiscy.py
Labels: testing

#40 Change parsing of result table of `predictprotein`
  src/cport/modules/predictprotein.py
  tests/test_predictprotein.py
Labels: bug, good first issue, predictor

#41 Implement output file
  .gitignore
  src/cport/cli.py
  src/cport/modules/loader.py
  src/cport/modules/utils.py
  tests/test_data/test_output.csv
  tests/test_utils.py
Labels: enhancement

#38 Update install instructions
  INSTALL.md
  README.md
  requirements.txt
Labels: documentation

#47 Add more code checks
  .github/workflows/lint.yml
Labels: testing

#48 more code linting
  .github/workflows/lint.yml
  .prospector.yml
  setup.py
  src/cport/__init__.py
  src/cport/cli.py
  src/cport/modules/__init__.py
  src/cport/modules/cons_ppisp.py
  src/cport/modules/error.py
  src/cport/modules/ispred4.py
  src/cport/modules/loader.py
  src/cport/modules/meta_ppisp.py
  src/cport/modules/predictprotein.py
  src/cport/modules/predus2.py
  src/cport/modules/scriber.py
  src/cport/modules/sppider.py
  src/cport/modules/utils.py
  src/cport/modules/whiscy.py
  src/cport/url.py
  src/cport/version.py
  tests/test_cons_ppisp.py
  tests/test_meta_ppisp.py
Labels: testing

#49 Implement `predictprotein` query via dedicated API
  src/cport/modules/loader.py
  src/cport/modules/predictprotein_api.py
  src/cport/url.py
  tests/test_predictprotein.py
Labels: enhancement, predictor

#51 bypass SSL certificate linter checks
  src/cport/modules/cons_ppisp.py
  src/cport/modules/meta_ppisp.py
  src/cport/modules/predus2.py
Labels: wontfix, testing

#52 added PSIVER prediction server
  .trunk/out
  .trunk/trunk.yaml
  README.md
  etc/config.json
  src/cport/modules/loader.py
  src/cport/modules/psiver.py
  src/cport/url.py
  tests/test_data/psiver_result.txt
  tests/test_psiver.py
Labels: predictor
